package flash.pipeline.runtime;

/**
 * Stable identifiers for external or startup-critical runtime dependencies.
 */
public enum DependencyId {
    PLUGIN_JAR_INTEGRITY,
    IMAGEJ_RUNTIME,
    BIO_FORMATS_RUNTIME,
    OBJECTS_COUNTER_3D,
    OBJECTS_COUNTER_3D_PLUS,
    MCIB3D_CORE,
    STARDIST_RUNTIME,
    TENSORFLOW_NATIVE_RUNTIME,
    APACHE_POI_RUNTIME,
    CELLPOSE_RUNTIME,
    EPFL_PSF_GENERATOR_RUNTIME,
    DECONV_CLIJ2_RUNTIME,
    DECONVOLUTIONLAB2_RUNTIME,
    ITERATIVE_DECONVOLVE_3D_RUNTIME,
    COLOC2_RUNTIME,
    IMGLIB2_ALGORITHM_RUNTIME,
    IMGLIB2_FFT_RUNTIME,
    JTRANSFORMS_RUNTIME,
    ORIENTATIONJ_RUNTIME,
    JTS_CORE
}
